### ISSUE TITLE
Sprint 2 - Tarea 2 - Modelar un empleado como una clase de Java

### ISSUE THREAD

**Issue by jahd66** [tecnolocos/ingresos_egresos_web#7]
Definition of done:
- Es posible crear una nueva instancia de la clase
"Empleado"
- Es posible leer y modificar el nombre de un empleado
- Es posible leer y modificar el correo de un empleado
- Es posible leer y modificar la empresa a la que el
empleado pertenece
- Es posible leer y modificar el rol del empleado
(administrador, operativo)

**Comment by j3nn3r97** [comment]
Hola , este seria el modelado de la clase empleado: 
[distribucion (4).pdf](https://github.com/tecnolocos/ingresos_egresos_web/files/9391110/distribucion.4.pdf)
mpleado:

**Comment by j3nn3r97** [comment]
Hola @jahd66 , ya se corrigió el diagrama; Contiene connotación camelcase y se soluciono el encapsulamiento de variables y métodos, adicional a esto y de acuerdo al diagrama en mención se creo la clase Empleado.java 
[ModeloClaseEmpleado.pdf](https://github.com/tecnolocos/ingresos_egresos_web/files/9396917/ModeloClaseEmpleado.pdf)
![image](https://user-images.githubusercontent.com/59620948/185998699-5d636aa9-e4ba-42dc-9e7c-f7f27ee2b143.png)

**Comment by jahd66** [comment]
Perfecto Jenner, gracias por adelantar bastante el proceso de modelado de la clase. Cuando puedas subes la clase a la branch del repositorio "development", ahí vamos mirando entre todos qué hace falta y qué ya completamos para dar por finalizado el sprint.
